---
plugins:
  - module: Check::User
    config:
      user: tokuhirom
  - module: Check::Network
    config:
      urls:
       - http://livedoor.com/
       - http://google.com/

  - module: Worker
    config:
      fork_num: 3
      gearman_servers:
        - 127.0.0.1

  - module: Agent::HTTP
    config:
      target: http://livedoor.com/
      user_agent: DoCoMo/1.0/P504i/c30/TB

  - module: Agent::FTP
    config:
      target: ftp.ring.gr.jp
      message: FTP server ready.

# - module: Agent::HTTP
#   config:
#     target:
#      - http://livedoor.com/
#      - http://ljkdlsjaflfvedoor.com/
#     user_agent: DoCoMo/1.0/P504i/c30/TB

# - module: Agent::DJabberd
#   config:
#     target:
#       - 127.0.0.1
#     admin_port: 33562

# - module: Agent::SNMPDisk
#   config:
#     target:
#       - 127.0.0.1

# - module: Agent::POP3S
#   config:
#     target:
#       - 127.0.0.1
#     port: 1122252

# - module: Agent::DBI
#   config:
#     target:
#       - dbi:
#     user: root
#     password: root

  - module: Agent::Gearmand
    config:
      target:
        - 127.0.0.1

  - module: Notify::Debug

