---
plugins:
  - module: Check::User
    config:
      user: tokuhirom
  - module: Check::Network
    config:
      urls:
       - http://livedoor.com/
       - http://google.com/
  - module: Worker
    config:
      fork_num: 3
      gearman_servers:
        - 127.0.0.1

